services:

  excalidraw:
    image: kiliandeca/excalidraw
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      BACKEND_V2_GET_URL: http://excalidraw-storage-backend:8080/api/v2/scenes/
      BACKEND_V2_POST_URL: http://excalidraw-storage-backend:8080/api/v2/scenes/
      HTTP_STORAGE_BACKEND_URL: http://excalidraw-storage-backend:8080/api/v2
      SOCKET_SERVER_URL: http://excalidraw-room:80/
      STORAGE_BACKEND: http

  excalidraw-storage-backend:
    image: kiliandeca/excalidraw-storage-backend
    restart: unless-stopped
    environment:
      STORAGE_URI: ${STORAGE_URI}
      PORT: 8080

  excalidraw-room:
    image: excalidraw/excalidraw-room
    restart: unless-stopped

  redis:
    image: redis
    restart: unless-stopped